// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250416184050_DB image")]
    partial class DBimage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coca-Cola"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fanta"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sprite"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dr. Pepper"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pepsi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "7UP"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mirinda"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Mountain Dew"
                        });
                });

            modelBuilder.Entity("Database.Models.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Denomination")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Denomination = 1,
                            IsBlocked = false,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 2,
                            Denomination = 2,
                            IsBlocked = false,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 3,
                            Denomination = 5,
                            IsBlocked = false,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 4,
                            Denomination = 10,
                            IsBlocked = false,
                            Quantity = 100
                        });
                });

            modelBuilder.Entity("Database.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Database.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerItem")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Database.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            ImageUrl = "/images/cola.jpg",
                            Name = "Напиток газированный Coca-Cola",
                            Price = 105m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            ImageUrl = "/images/fanta.jpg",
                            Name = "Напиток газированный Fanta",
                            Price = 98m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            ImageUrl = "/images/sprite.jpg",
                            Name = "Напиток газированный Sprite",
                            Price = 83m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            ImageUrl = "/images/dr_pepper.jpg",
                            Name = "Напиток газированный Dr. Pepper Zero",
                            Price = 110m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            ImageUrl = "/images/pepsi.jpg",
                            Name = "Напиток газированный Pepsi",
                            Price = 95m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 6,
                            ImageUrl = "/images/7up.jpg",
                            Name = "Напиток газированный 7UP",
                            Price = 85m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 7,
                            ImageUrl = "/images/mirinda.jpg",
                            Name = "Напиток газированный Mirinda",
                            Price = 92m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 8,
                            ImageUrl = "/images/dew.jpg",
                            Name = "Напиток газированный Mountain Dew",
                            Price = 100m,
                            Quantity = 6
                        });
                });

            modelBuilder.Entity("Database.Models.OrderItem", b =>
                {
                    b.HasOne("Database.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Database.Models.Product", b =>
                {
                    b.HasOne("Database.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Database.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Database.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
